RateProf/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls.conf import include
from rate.views import *
import django.contrib.auth.views as auth_views
from rate.forms import *

urlpatterns = [
    
    url('admin/', admin.site.urls),
    url('rate/',include("rate.urls")),
    url(r'accounts/profile/$',UserProfile,name='user_profile'),
    url(r'accounts/profile/clear/$',ClearUserWarnings,name='clear_warnings'),
    url(r'accounts/login/', auth_views.LoginView.as_view(authentication_form=AuthenticationFormCheckBanned), name='user_login'),
    url(r'accounts/logout', LogoutLog.as_view(),name="logout"),
    # url(r'^oauth/', include('social_django.urls', namespace='social')),
    url('accounts/', include('django.contrib.auth.urls')),
    
    
    url(r'^signup/$', UserCreateView.as_view(), name="signup"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    url(r'accounts/', include('allauth.urls')),
]

rate/urls.py
from django.urls import path
from django.conf.urls import url
from rate.views import *
# import rate

urlpatterns = [
    url('^index/$', index, name="index"),

    url(r'^like/(?P<pk>[0-9]+)$',LikeReview,name="like"),
    url(r'^dislike/(?P<pk>[0-9]+)$',DislikeReview,name="dislike"),
    
    url(r'^report/(?P<pk>[0-9]+)/$',ReportCreateView.as_view() , name="report"),
    # url(r'^profs/(?P<prof_id>[0-9]+)/$', ProfPage, name="p_data"),
    url(r'^profs/(?P<pk>[0-9]+)/$', ProfPage, name="p_data"),
    url(r'^profs/(?P<pk>[0-9]+)/create/$',ProfReviewCreateView.as_view(), name="prof_review"),
    url(r'^profs/',ProfsListView.as_view(),name="profs"),
    
    # url(r'^courses/(?P<course_id>[0-9]+)/$',CoursePage,name="c_data"),
    url(r'^courses/(?P<pk>[0-9]+)/$',CoursePage,name="c_data"),
    url(r'^courses/(?P<pk>[0-9]+)/create/$',CourseReviewCreateView.as_view(), name="course_review"),
    url(r'^courses/', CoursesListView.as_view(), name="courses"),
]

rate/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime as dt
# Create your models here.
class Dept(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Review(models.Model):


    RatingChoices = (
        (0, "Poor"),
        (1, "Bad"),
        (2, "Average"),
        (3, "Above Average"),
        (4, "Good"),
        (5, "Excellent"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True,null=True)

    comment = models.TextField(max_length=4096)
    isAnonymous = models.BooleanField(default=False,verbose_name="Remain Anonymous?")
    
    prof = models.ForeignKey("Profs", on_delete=models.CASCADE,null=True)
    course = models.ForeignKey("Courses", on_delete=models.CASCADE,null=True)
    
    difficulty = models.IntegerField(choices = RatingChoices,default=0)
    content_quality =models.IntegerField(choices = RatingChoices,default=0)
    grading = models.IntegerField(choices = RatingChoices,default=0)
    attendance = models.IntegerField(choices = RatingChoices,default=0)
    overall_rating =models.IntegerField(choices = RatingChoices,default=0)

    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        p_name=""
        c_name=""
        if self.prof is None:
            p_name = "None"
        else:
            p_name = self.prof.name
        if self.course is None:
            c_name = "None"
        else:
            c_name = self.course.code
        
        return f"Prof - {p_name} | Course - {c_name} | Rating - {str(self.overall_rating)} | User - {self.user.username}"
        
    


class Profs(models.Model):
    dept = models.ForeignKey("Dept", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    webpage = models.URLField(max_length=200)
    # pic_url = models.URLField(max_length=200)

    def __str__(self):
        return f"Dept -> {self.dept.name} | Name -> {self.name}"
    


class Courses(models.Model):
    dept = models.ForeignKey("Dept", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=10)

    def __str__(self):
        return self.code

class ReportReview(models.Model):
    SPAM = "Spam"
    FRAUD = "Fraud"
    OFFENSIVE = "Offensive"

    CategoryChoices = (
        (SPAM, "Spam"),
        (FRAUD, "Fraud"),
        (OFFENSIVE, "Offensive"),
    )

    review = models.ForeignKey("Review", on_delete=models.CASCADE)
    reporting_user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=50, choices=CategoryChoices)
    reason = models.TextField(verbose_name="Please specify any other details", max_length=5000)

    def __str__(self):
        return f"Category : {self.category} | Reported User : {self.review.user.username}" 
    
    @property
    def reported_user(self):
            return self.review.user
   
class Warnings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()


class Banned(models.Model):
    PERMANENT = "Banned Permanently"
    FREE = "Free to relieve"
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ban_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    ban_duration = models.DurationField(null=True)
    permanent_ban = models.BooleanField(default=False)

    @property
    def ban_relieve(self):
        if(not self.permanent_ban):
            return self.ban_date + self.ban_duration
        else:
            return self.PERMANENT

    @property
    def time_to_relieve(self):
        if(not self.permanent_ban):
            if(self.ban_relieve > dt.today()):
                a = self.ban_relieve - dt.today()
                return f"{a.days} days,{a.seconds//3600} hours"
            else:
                return self.FREE
        else:
            return self.PERMANENT
    
    def __str__(self):
        return self.user.__str__()
    

class Activity(models.Model):
    LIKE = "Like"
    DISLIKE = "Disike"
    SIGNUP = "Signup"
    LOGIN = "Login"
    LOGOUT = "Logout"
    COMMENT = "Comment"
    REPORT = "Report"
    CategoryChoices = (
        (COMMENT,"Comment"),
        (REPORT,"Report"),
        (LOGIN,"Login"),
        (LOGOUT,"Logout"),
        (SIGNUP,"Signup"),
        (LIKE,"Like"),
        (DISLIKE,"Dislike"),
    )

    category = models.CharField(choices=CategoryChoices, max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    log = models.TextField(null=True)
    def __str__(self):
        return f"{self.category} | user : {self.user}"

    def login_log(self):
        self.log = f"{self.user} Logged in "
    
    def signup_log(self):
        self.log = f"{self.user} Signed up "

    def logout_log(self):
        self.log = f"{self.user} Logged out "

    def comment_log(self,review):
        self.log = f"{self.user} added a comment to {review.prof} and {review.course} with comment {review.comment}"

    def report_log(self,report):
        self.log = f"{self.user} reported a comment by {report.reported_user} on prof {report.review.prof} and course {report.review.course}"

    def like_log(self,review):
        self.log = f"{self.user} Liked a comment by {review.user} on prof {review.prof.name} and course {review.course.code}"

    def dislike_log(self,review):
        self.log = f"{self.user} Disliked a comment by {review.user} on prof {review.prof.name} and course {review.course.code}"

     
class Credibility(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)
    trust = models.IntegerField(default=0)

    def __str__(self):
        return f"User - {self.user} | Trust {self.trust}"
    

rate/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from rate.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import re


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True,help_text="Email is Required")
    first_name = forms.CharField(max_length=50, required=False,help_text="Optional")
    last_name = forms.CharField(max_length=50, required=False, help_text="Optional")

    class Meta:
        model = User
        fields = ('username','password1','password2','email','first_name','last_name')

    def save(self, commit=True):
        user = super().save(commit=commit)
        return user

    def is_valid(self):
        valid = super().is_valid()
        
        if not valid:
            return valid
        
        email = self.cleaned_data['email']
        r1 = re.compile('(.*)@.*iitd.ac.in')
        match = r1.search(email)
        if(match is None):
            self._errors[''] = "This portal is only for IITD students. Trespassers will be hacked!!"
            return False
        kerb_id = match.groups(1)[0]
        users = User.objects.filter(email__endswith="iitd.ac.in").filter(email__startswith=kerb_id)
        if (len(users) != 0):
            print(users)
            self._errors[''] = "This email address already exists. Try fooling someone else!!"
            return False

        return valid


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['prof', 'course', 'difficulty', 'content_quality',
              'grading', 'attendance', 'overall_rating', 'isAnonymous', 'comment']
    
    def __init__(self,*args, **kwargs):
        print(kwargs)
        
        super(ReviewForm,self).__init__(*args, **kwargs)
        if "prof" in kwargs["initial"]:
            prof = kwargs["initial"].pop("prof")
            self.fields["prof"].queryset = Profs.objects.filter(id=prof.id)
            # print(self.fields["prof"].queryset)
            self.fields["course"].queryset = prof.dept.courses_set.all()
        
        if "course" in kwargs["initial"]:
            course = kwargs["initial"].pop("course")
            self.fields["course"].queryset = Courses.objects.filter(id=course.id)
            self.fields["prof"].queryset = course.dept.profs_set.all()
        

class AuthenticationFormCheckBanned(AuthenticationForm):
    def confirm_login_allowed(self, user):
        bl = user.banned_set.all()
        if (bl and bl[0].time_to_relieve != Banned.FREE):
            msg = "Your account has been banned "
            if("permanent" in bl[0].time_to_relieve):
                msg += "PERMANENTLY"
            else:
                msg += "for " + bl[0].time_to_relieve
            raise forms.ValidationError(
                (msg),
                code='inactive',
            )
        else:
            if bl:
                bl[0].delete()
            login_activity = Activity(user=user,category=Activity.LOGIN)
            login_activity.login_log()
            login_activity.save()

rate/templates/base.html
<style>
nav ul {
  list-style-type: none;
  margin: 10px;
  padding:10px;

}

nav li {
    display:inline;
    margin:10px;
}
</style>

<nav>
<ul>
<li>
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}"> Logout {{user.username}} </a>
    {% else %}
    <a href = "{% url 'login' %}"> Login </a>
    {% endif %}
<li> <a href="{% url 'signup' %}"> Sign Up </a>
<li> <a href="{% url 'profs' %}"> Rate Profs</a>
<li> <a href="{% url 'courses' %}"> Rate Courses</a>
<li> <a href="{% url 'user_profile' %}"> My Profile</a>

</ul>
</nav>

{% block base_body %}
{% endblock base_body %}

rate/templates/detail.html
{% extends 'base.html' %}

{% block base_body %}

<div id = "bio">
    {% block bio %}
    {% endblock bio%}
</div>

<div id="reviews">
<h2> REVIEWS </h2>

</div>

<div id ="add_review">
<ol>
{% for review in reviews %}
{% include "display_review.html" %}
{% endfor %}
</ol>
</div>


{% endblock base_body %}

{% comment %} 
<script>
    function Disable(){
  document.getElementById("add_review").style.visibility = "visible"
  }
</script>
<div id = "add_review" style="visibility:hidden">

{% if user.is_authenticated %}
    <p> Congrats now u can add a comment </p>
{% else %}
<p> You must be logged in to add a review
    <a href= "{% url 'login' %}?redirect_to={{request.path}}"> Click here to login </a>
{% endif %}
 

</div>
{% endcomment %}

rate/templates/display_review.html
        <li>
            {% if review.isAnonymous %}
                <h4> NAME: ANONYMOUS </h4>
            {% else %} 
                <h4> NAME: {{review.user.first_name}} {{review.user.last_name}}
            {% endif %}
            {% if review.prof is not None %}
            <h5> PROF : {{review.prof.name}} </h5>
            {% endif %}
            {% if review.course is not None %}
            <h5> COURSE : {{review.course.code}} </h5>
            {% endif %}
            {% if review.user.credibility %}
            <h5> CREDIBILITY : {{review.user.credibility.trust}} </h5>
            {% endif %}
             <textarea name="text" wrap="hard" rows="5" cols="20" readonly > {{review.comment}} </textarea>
            <div class = "ratings">
                <ul>
                    <li> Difficulty : {{review.get_difficulty_display}}
                    <li> Content Quality : {{review.get_content_quality_display}}
                    <li> Grading : {{review.get_grading_display}}
                    <li> Attendance : {{review.get_attendance_display}}
                    <li> <b> Overall Rating : {{review.get_overall_rating_display}} </b>
                </ul>
            </div>
            <div>
            <p> Likes : {{review.likes}} | Dislikes : {{review.dislikes}} </p>
            </div>
            {% if review.user != user %}
            <p> <a href = {% url 'report' review.id%}> Click here to report this </a></p>
            <button type="submit" name="like"  onclick = "location.href =  '{% url 'like' review.id%}'">Like</button>
            <button type="submit" name="dislike"  onclick = "location.href = '{% url 'dislike' review.id%}'">Dislike</button>
            {% endif %}

rate/templates/index.html
{% extends 'base.html' %}
{% block base_body %}
<p> This is my Profs and Course Rating system</p>
{% endblock base_body %}

rate/templates/list.html
{% extends 'base.html' %}
{% block base_body %}
<ul>
{% for dept in dept_list %}
    <li> <h2> {{dept.name}}</h2>
        <ul>
        {% block body %}
        {% endblock %}
        </ul>
{% endfor %}
</ul>
{% endblock base_body %}

rate/templates/profile.html
{% extends 'base.html' %}

{% load socialaccount %}

{% block base_body %}
<h1> Hello {{user.first_name}} </h1>
<ul>
<li> Username: {{user.username}}
<li> Email Address : {{user.email}}
<li> Trust : {{user.credibility.trust}}

</ul>

{% get_social_accounts user as accounts %}
{% if accounts.google %}
<h3> Account successfully linked with google</h3>
{% else %}
<a href="{% provider_login_url "google" process="connect" %}"> Click here to link your account with google</a>
{% endif %}
<br/>
{% if accounts.github %}
<h3> Account successfully linked with Github </h3>
{% else %}
<a href="{% provider_login_url "github" process="connect" %}"> Click here to link your account with github </a>
{% endif %}



{% if user.warnings_set.all %}
<ol>
{% for warning in user.warnings_set.all %}
<li> <textarea cols = "40" rows = "10" readonly> {{warning.message}}</textarea>
{% endfor %}
</ol>
<a href = "{% url 'clear_warnings' %}"> Ok I have understood, I will take care in th future. Clear the warnings</a>
{% endif %}


<h2><u> Recent Reviews </u></h2>
<ol>
{% for review in reviews %}
    <h3> Timestamp : {{review.timestamp}} </h3>
    {% include "display_review.html" %}
    
{% endfor %}
</ol>
{% endblock base_body %}